# Generated by Django 3.2.4 on 2021-07-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApp', '0005_auto_20210708_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolereq',
            name='rltype',
            field=models.IntegerField(choices=[(2, 'Manager'), (3, 'User')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Guest'), (2, 'Manager'), (3, 'User')], default=1),
        ),
    ]
